### ISSUE TITLE
Please consider adding a license to the repository

### ISSUE THREAD

**Issue by Michael-S** [melezhik/Sparrow6#1]
I see that the META6.json file references the Artistic license, is that the license for the whole project?

Would it make sense to add a separate LICENSE or COPYING file to this repository, and maybe to the sparrow-plugins repository?

**Comment by melezhik** [comment]
@Michael-S 
hi Mike! It would help if you  specify what exactly you are trying to change, ask. Is it a license type for Sparrow6 project?

**Comment by Michael-S** [comment]
Hello melezhik!
Yes, I would just like to know what conditions there are for using Sparrow6.

I'm not trying to change anything yet, I was just starting to play with Sparrow6 for my personal computers.  It is not part of any deployment or business.  I just like Perl6/Raku and this seems like it could be a fun way for me to use it.

**Comment by melezhik** [comment]
hi @Michael-S  first of all thank you for your interest in the Sparrow. ☺️

Honestly. I have no particular reasons why I chose artistic license. Is it a problem for you to start using Sparrow?

**Comment by Michael-S** [comment]
No, not at all.  I just wasn't sure if its reference in META6.json was sufficient.  I think that's hard to find for someone that doesn't know what they are.  I thought a separate LICENSE file would be good.

**Comment by melezhik** [comment]
I see. i could add the file to repository. anyway i think  so far artistic license is a current license for Sparrow. I think the same will be for sparrow plugins  repisitory.

let me know if you need any further help with Sparrow.

**Comment by Michael-S** [comment]
Thank you.
