### ISSUE TITLE
Lack of general info about Sparrow for a beginner

### ISSUE THREAD

**Issue by vrurg** [melezhik/Sparrow6#2]
I think it's a good place to explain my point of Sparrow lacking on easy to grasp description.

Basically, I saw almost every single post and article about Sparrow here and there. Not every I read fully through though, but those were mostly about some particular use cases. The problem about all of them, as I stated once, is that they focus on _how_ but don't answer _why_. Why should one use Sparrow? What problem does Sparrow solve?

Ok, I saw you naming it an _automation framework_. Fine, but I don't know what is it. If memory serves me right, it was once compared to Ansible, but I never used it. And it is unlikely I'd open Wikipedia to read about it because I'm under-motivated for this. Things mostly work for me.

All this point I could sum up in a simple question: what does make Sparrow better than just writing a script to have a task done?

I think, something of the kind user dominix was asking you about in a comment to https://dev.to/melezhik/informal-introduction-into-sparrow6-40pa. It's not that they need more examples.

It really feels to me that you could gain more of a user base if you find the right words to persuade people.

**Comment by melezhik** [comment]
Hi @vrurg thanks for feedback.

Let me try )))

Sparrow is trying to solve a following type of tasks

* I need to script some task, I want to do this with minimal efforts
* I want to distribute my work among others with minimal efforts

# I need to script some task, I want to do this with _minimal_ efforts

Raku is great. But Raku misses some libraries, moreover some libraries already solve a problem in most efficient way. By libraries I don't mean only software packages but also other languages and tools. A good example is Bash. Many people "hate" Bash, but it's really an efficient for certain type of tasks. Sparrow is really good at gluing Bash scripts together and expose them as Raku functions or as a CLI:

`task.bash`

```bash
sudo apt-get install config()<list>
```

Raku high level code:

```raku
use Sparrow6::DSL;
# install my favorite packages
task-run ".", %(
  list => "rakudo nginx nano"
);
```

Or as a CLI: 

```bash
s6 --task-run .@list="rakudo nginx nano"
```

So the philosophy of Sparrow - let other tools do what they can do best and let Raku provide you with high level orchestration ...

#  I want to distribute my work among others with minimal efforts

Now I want other people don't reinvent a wheel and share fruits of my work. That's dead easy with Sparrow:

`sparrow.json`

```json
{
 "name" : "package-installer",
  "version" : "0.0.1",
  "description" : "apt package installer"
}
```

```bash
s6 --upload
```

On another host:

As a  CLI 

```bash
s6 --index-update
s6 --plg-run @package-installer@list='rakudo nginx nano'
```

Or as  a Raku API

```raku
use Sparrw6::DSL;

task-run "install my packages", "package-installer", %( 
 list => qq[rakudo nginx nano]  
)

``` 

Hope this crash course will give you some clarity, feel free to ask more ...

**Comment by melezhik** [comment]
cc @thibaultduponchelle

**Comment by melezhik** [comment]
And for that bit:

>  what does make Sparrow better than just writing a script to have a task done?

Sparrow is a script orchestrator. You write underlying code on script's language that fits best to a domain of a task being solved ( not all the languages solve tasks equally efficiently, so you find the best one).  From high level  you  get scripts as Raku functions.

When writing scripts on different languages you also benefit from a unified [Sparrow API](https://github.com/melezhik/Sparrow6/blob/master/documentation/development.md) that takes care of typical scripting challenges - configuration, parsing parameters and testing  ( all this, for example a big problem for Bash ).

**Comment by thibaultduponchelle** [comment]
What would be the solution for this? A big tuto/doc that explains automation and sparrow concepts ? Maybe the documentation folder is a good start (but is not the answer to this) ?

**Comment by melezhik** [comment]
@vrurg maybe this could be helpful as well - https://dev.to/thibaultduponchelle/what-if-i-tell-you-sparrow-3bed

**Comment by melezhik** [comment]
@vrurg I am closing this if you don't any more clarification
