### ISSUE TITLE
Is sparrowhub.io down?

### ISSUE THREAD

**Issue by gitjeff2** [melezhik/Sparrow6#3]
It seems that sparrowhub.io is down.

**Comment by melezhik** [comment]
Hi @gitjeff2 , yes it is. In my plans to resurrect it. Are you planing to use Sparrowhub/Sparrow?. Till I restore SparrowHub there is simple way to host SparrowHub plugins (if you need _just_ a repository ), just using nginx:

https://github.com/melezhik/Sparrow6/blob/master/documentation/repository.md#create-repository

**Comment by gitjeff2** [comment]
Yes, I'll be experimenting with it quite extensively over the next few months in my home lab. I know running a FOSS project can be thankless sometimes, but please keep this up. This is very worthwhile stuff you're building.

**Comment by melezhik** [comment]
Thanks for support @gitjeff2 . Right now Sparrow in slow mode for many reasons. But I think I'll be able to help with maintenance and fixing bug if required. 

I am interested to know for what tasks/purposes you are going to use Sparrow?

**Comment by gitjeff2** [comment]
> I am interested to know for what tasks/purposes you are going to use Sparrow?

Mainly, switch configuration and provisioning of Raspberry Pi's. My switch isn't Cisco or Juniper so it has some weird XML-driven interface (SOAP, I think.) I need to sort that out so that I can use Sparrow to dynamically power up Pi's. Once their up, provisioning or re-imaging a Pi should be simple enough. I'm sure there will also be some VLAN stuff in the mix, too.

Is there a SOAP plugin for Sparrow? I didn't see one, but I could have just missed it.

**Comment by melezhik** [comment]
I am not sure if Sparrow has any plugins to work with SOAP protocol. BTW, i don't understand little in PI's , which protocol is used to power them up and provision. I guess an SSH for provision at least?

**Comment by gitjeff2** [comment]
> I am not sure if Sparrow has any plugins to work with SOAP protocol.

That's alright, it will do me good to figure out how to write my own Sparrow plugin. 

> [W]hich protocol is used to power them up and provision. I guess an SSH for provision at least?

So, a stock Pi powers up as soon as it's connected to a USB cable. But, a common add-on is a PoE "hat" which sits on top of the Pi and provides Power-over-Ethernet support. You're right about SSH. By default, the stock OS disables SSH at startup. There is a well supported method for editing the OS image to change this. Also, there are firmware options to enable the Pi to boot over the network directly at power on. I've never used network boot, so I don't know with 100% certainty, but I think it's driven by TFTP.

**Comment by melezhik** [comment]
> That's alright, it will do me good to figure out how to write my own Sparrow plugin.

👍 here is some links to help ( from high to low level )

* https://dev.to/melezhik/informal-introduction-into-sparrow6-40pa
* https://dev.to/melezhik/sparrowhub-io-repository-of-devops-and-automation-utilities-4mk8
* https://raku-advent.blog/2020/12/07/mixing-bash-and-raku-using-sparrow/
* https://github.com/melezhik/Sparrow6/blob/master/documentation/plugins.md
* https://github.com/melezhik/Sparrow6/blob/master/documentation/repository.md
* https://github.com/melezhik/Sparrow6/blob/master/documentation/development.md



As for SSH. If you are going to provision PI's using SSH, 2 things to consider:

* [sparrowdo](https://github.com/melezhik/sparrowdo) which bootstraps sparrow env  and runs sparrow scenarios over ssh
* rakudo should be installed at PI as currently sparrowdo does not support Sparrow bootstrap for PI's os - https://github.com/melezhik/sparrowdo/blob/master/resources/bootstrap.sh

**Comment by gitjeff2** [comment]
Thanks for the info! BTW, the first ever [Raku conference](https://conf.raku.org/) is coming up in August. It's 100% virtual. You might consider giving a talk to showcase Sparrow. There are even 5 minute "lightning talk" slots available if a 20 minute slot is too long.

**Comment by melezhik** [comment]
Yeah. Thanks. I will think about it 😊

**Comment by melezhik** [comment]
Sparrowhub.io is restored
