### ISSUE TITLE
Use .raku instead of .pl6 in documentation/development guide

### ISSUE THREAD

**Issue by tbrowder** [melezhik/Sparrow6#4]

**Comment by melezhik** [comment]
Hi @tbrowder thanks! This was in my plans.

**Comment by tbrowder** [comment]
My pleasure. I really want to use Sparrow to manage my cloud servers, so I’ve been browsing your docs.

**Comment by melezhik** [comment]
Implemented in this version - https://raku.land/zef:melezhik/Sparrow6/changes?v=0.0.37
